name: led-blink
base: core24
version: '0.1'
summary: Demonstration app using Ubuntu Core and a Raspberry Pi.
description: This is a small app used to demonstrate using Ubuntu Core with a Raspberry Pi.
  LED blinks on GPIO 24 or pin 18 of Raspberry Pi.

platforms:
  arm64:
    build-on: [arm64]  # Launchpad will build on arm64
    build-for: [arm64]

grade: stable
confinement: strict

apps:
  led-blink:
    daemon: simple
    command: bin/led-blink
    plugs:
      - gpio-control

plugs:
  gpio-control:
    interface: gpio-control
    gpiochip: "0"
  gpio-dev:
    interface: system-files
    write:
      - /dev/gpiochip0
      - /dev/gpiochip1

parts:
  led-blink:
    plugin: cmake
    source: .
    cmake-generator: Unix Makefiles
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=
    build-packages:
      - build-essential
      - libgpiod-dev
    stage-packages:
      - libc6
      - libgpiod2